//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4961.
// 
namespace Mobile_July.svumobilesales.somee.com {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://svumobilesales.somee.com/Service1.asmx")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://svumobilesales.somee.com/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://svumobilesales.somee.com/Service1.asmx/HelloWorld", RequestNamespace="http://svumobilesales.somee.com/Service1.asmx", ResponseNamespace="http://svumobilesales.somee.com/Service1.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://svumobilesales.somee.com/Service1.asmx/Op", RequestNamespace="http://svumobilesales.somee.com/Service1.asmx", ResponseNamespace="http://svumobilesales.somee.com/Service1.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Op(int _op, string tablename, string[] _Params) {
            this.Invoke("Op", new object[] {
                        _op,
                        tablename,
                        _Params});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOp(int _op, string tablename, string[] _Params, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Op", new object[] {
                        _op,
                        tablename,
                        _Params}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndOp(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://svumobilesales.somee.com/Service1.asmx/GET_Op", RequestNamespace="http://svumobilesales.somee.com/Service1.asmx", ResponseNamespace="http://svumobilesales.somee.com/Service1.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GET_Op(string tablename, string _QUERY, object[] _Params) {
            object[] results = this.Invoke("GET_Op", new object[] {
                        tablename,
                        _QUERY,
                        _Params});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGET_Op(string tablename, string _QUERY, object[] _Params, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GET_Op", new object[] {
                        tablename,
                        _QUERY,
                        _Params}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGET_Op(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
